import Link from "next/link";
import { notFound } from "next/navigation";

const details = {
  "education-des-filles": { eyebrow:"Éducation des filles", title:"L’école ouvre des chemins qui durent toute une vie.", image:"/images/education-program.png", visual:"/images/education-detail.png", audience:"Les jeunes filles et les jeunes en âge d’apprendre, ainsi que leurs familles et communautés.", intro:"La fondation encourage l’éducation de la jeune fille et combat les obstacles qui empêchent les enfants de poursuivre leur scolarité.", sections:[["Centres éducatifs","Créer des espaces d’apprentissage ouverts aux jeunes, centrés sur l’alphabétisation, la lecture, le calcul et le développement des compétences de vie."],["Soutien à la scolarisation","Repérer les parcours fragilisés et aider les filles à rester engagées dans l’apprentissage lorsque des freins familiaux, sociaux ou économiques apparaissent."],["Sensibilisation des familles","Dialoguer avec les parents et les communautés autour de l’importance de l’éducation des filles, notamment là où certaines traditions rendent l’accès à l’école plus difficile."]], steps:[["Écouter","Échanger avec les familles, les éducateurs et les jeunes pour identifier les obstacles qui freinent la scolarisation."],["Accompagner","Mettre en place des actions d’information, d’orientation et de soutien éducatif adaptées au contexte local."],["Faire durer","Encourager une communauté de soutien autour des filles afin que leur parcours se poursuive au-delà d’une aide ponctuelle."]] },
  "protection-et-sante": { eyebrow:"Protection & santé", title:"Protéger, prévenir, accompagner avec respect.", image:"/images/health-program.png", visual:"/images/health-protection-detail.png", audience:"Les jeunes filles exposées au mariage précoce, les femmes âgées isolées et les personnes sans abri.", intro:"La fondation soutient et protège les jeunes filles et les personnes âgées dans l’Extrême-Nord du Cameroun, avec une attention particulière aux situations de vulnérabilité.", sections:[["Prévenir le mariage précoce","Sensibiliser aux conséquences du mariage des filles de moins de 16 ans, dont les risques de fistule et l’abandon dans certains mariages polygames."],["Soutenir les aînés","Prendre soin des femmes âgées abandonnées ou exclues de leur communauté, notamment à travers un accompagnement et des solutions d’hébergement."],["Mettre à l’abri","Fournir un abri et un soutien aux personnes sans domicile pour les protéger des abus, de l’exploitation et des violences."]], steps:[["Informer","Organiser des temps de sensibilisation accessibles autour de la protection, de la santé et des droits des jeunes filles."],["Orienter","Créer un lien de confiance pour que les personnes concernées puissent être écoutées et orientées vers un soutien adapté."],["Protéger","Mobiliser les ressources de proximité pour renforcer la sécurité, la dignité et l’accès à un environnement protecteur."]] },
  "autonomie-des-femmes": { eyebrow:"Autonomie des femmes", title:"Faire de l’activité économique une porte vers l’indépendance.", image:"/images/volunteers-banner.png", visual:"/images/women-autonomy-detail.png", audience:"Les groupes et collectifs de femmes qui souhaitent faire émerger ou consolider une activité génératrice de revenus.", intro:"La fondation promeut des activités génératrices de revenus durables au sein des groupes et collectifs de femmes.", sections:[["Agrobusiness local","Soutenir le développement d’activités agricoles pensées selon les réalités locales et les capacités des collectifs."],["Élevage de lapins","Encourager l’élevage de lapins comme activité productive, accessible et créatrice de revenus."],["Accompagnement collectif","Favoriser la coopération, le partage de compétences et l’émergence de projets économiques portés par les femmes elles-mêmes."]], steps:[["Faire émerger","Identifier avec les collectifs les savoir-faire, les opportunités et les activités qui répondent à leur environnement."],["Se former","Favoriser le partage de pratiques et l’acquisition de compétences utiles à la conduite d’une activité."],["Développer","Accompagner les groupes dans une dynamique durable, collaborative et tournée vers l’amélioration des revenus."]] }
};

export function generateStaticParams(){ return Object.keys(details).map((slug)=>({slug})); }

export default async function ActionDetail({ params }) { const { slug } = await params; const action = details[slug]; if(!action) notFound(); return <main className="page-shell"><section className="detail-lede section-wide"><div><p className="eyebrow">{action.eyebrow}</p><h1>{action.title}</h1><p>{action.intro}</p><Link className="button button-ink" href="/contact">Soutenir cette action <span>→</span></Link></div><img src={action.image} alt="" /></section><section className="detail-body section-wide"><p className="eyebrow">Ce que nous faisons</p><div className="detail-grid">{action.sections.map(([heading,text], index)=><article key={heading}><span>0{index+1}</span><h2>{heading}</h2><p>{text}</p></article>)}</div></section><section className="action-feature section-wide"><img src={action.visual} alt="" /><div><p className="eyebrow">Au cœur de l’action</p><h2>Des réponses construites avec les personnes concernées.</h2><p>Nous privilégions une approche de proximité : écouter, comprendre les réalités de terrain et faire grandir des solutions utiles avec les personnes, les familles et les acteurs locaux.</p><div className="audience-note"><span>Pour qui ?</span><p>{action.audience}</p></div></div></section><section className="action-steps section-wide"><p className="eyebrow">Notre approche</p><h2>Agir pas à pas, avec constance.</h2><div>{action.steps.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="back-band"><Link href="/actions">← Retour à toutes nos actions</Link><Link className="button button-sun" href="/engager">Je m’engage <span>→</span></Link></section></main>; }
