import Link from "next/link";
import { notFound } from "next/navigation";

const articles = {
  "ensemble-pour-education-des-filles": { category:"Éducation", title:"Ensemble pour l’éducation des filles", intro:"L’éducation des filles n’est pas seulement une question d’accès à l’école. C’est une manière de renforcer l’autonomie, les choix et les perspectives de toute une communauté.", image:"/images/education-program.png" },
  "activites-generatrices-de-revenus": { category:"Autonomie", title:"Des activités qui renforcent l’autonomie des femmes", intro:"Lorsque les femmes disposent de revenus durables, elles renforcent leur capacité à faire des choix pour elles-mêmes, leurs familles et leur communauté.", image:"/images/volunteers-banner.png" },
  "proteger-les-plus-vulnerables": { category:"Protection", title:"Protéger les personnes les plus vulnérables", intro:"Protéger les jeunes filles, les personnes âgées et les personnes sans abri est une responsabilité collective qui commence par l’écoute et l’attention.", image:"/images/health-program.png" }
};

export function generateStaticParams(){return Object.keys(articles).map((slug)=>({slug}));}

export default async function ArticlePage({params}){const {slug}=await params;const article=articles[slug];if(!article)notFound();return <main className="page-shell"><article className="article"><header className="article-header"><p className="eyebrow">{article.category} · Actualités</p><h1>{article.title}</h1><p>{article.intro}</p></header><img className="article-cover" src={article.image} alt="" /><div className="article-content"><p>La Fondation Bello et Bisso Charity Foundation agit dans l’Extrême-Nord du Cameroun afin de faire émerger des réponses concrètes aux situations de vulnérabilité. Cette page constitue un modèle éditorial prêt à accueillir les récits, bilans de terrain, témoignages et annonces de la fondation.</p><h2>Des actions pensées avec les communautés</h2><p>Les projets de la fondation s’appuient sur le dialogue avec les personnes concernées et les réalités de leur environnement. Ils visent à renforcer les capacités, la protection et les possibilités d’avenir.</p><blockquote>« Chaque initiative prend son sens lorsqu’elle permet aux personnes de retrouver de la sécurité, des choix et de la confiance. »</blockquote><h2>Suivre et partager l’élan</h2><p>Retrouvez prochainement ici les informations sur les programmes, les temps forts, les partenariats et les façons de contribuer à cette dynamique.</p><Link className="button button-ink" href="/contact">Prendre contact <span>→</span></Link></div></article><section className="back-band"><Link href="/blog">← Retour aux actualités</Link><Link className="button button-sun" href="/engager">S’engager <span>→</span></Link></section></main>; }
